In [2]:
mongodb+srv://navinxqz:#Navin@477@cluster0.am2sy53.mongodb.net/?appName=Cluster0

SyntaxError: invalid syntax (4021629578.py, line 1)

In [1]:
print("Hello World")

Hello World

In [3]:
import pandas as pd

In [5]:
data = pd.read_csv("D:\\Inception FSDS\\Inception-FSDS-classwork\\classwork\\Day26_Database\\healthcare-dataset-stroke-data.csv")

In [6]:
data

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,9046,Male,67.0,0,1,Yes,Private,Urban,228.69,36.6,formerly smoked,1
1,51676,Female,61.0,0,0,Yes,Self-employed,Rural,202.21,NaN,never smoked,1
2,31112,Male,80.0,0,1,Yes,Private,Rural,105.92,32.5,never smoked,1
3,60182,Female,49.0,0,0,Yes,Private,Urban,171.23,34.4,smokes,1
4,1665,Female,79.0,1,0,Yes,Self-employed,Rural,174.12,24.0,never smoked,1
...,...,...,...,...,...,...,...,...,...,...,...,...
5105,18234,Female,80.0,1,0,Yes,Private,Urban,83.75,NaN,never smoked,0
5106,44873,Female,81.0,0,0,Yes,Self-employed,Urban,125.20,40.0,never smoked,0
5107,19723,Female,35.0,0,0,Yes,Self-employed,Rural,82.99,30.6,never smoked,0
5108,37544,Male,51.0,0,0,Yes,Private,Rural,166.29,25.6,formerly smoked,0
5109,44679,Female,44.0,0,0,Yes,Govt_job,Urban,85.28,26.2,Unknown,0

In [7]:
data.head()

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,9046,Male,67.0,0,1,Yes,Private,Urban,228.69,36.6,formerly smoked,1
1,51676,Female,61.0,0,0,Yes,Self-employed,Rural,202.21,NaN,never smoked,1
2,31112,Male,80.0,0,1,Yes,Private,Rural,105.92,32.5,never smoked,1
3,60182,Female,49.0,0,0,Yes,Private,Urban,171.23,34.4,smokes,1
4,1665,Female,79.0,1,0,Yes,Self-employed,Rural,174.12,24.0,never smoked,1

In [8]:
data.tail()

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
5105,18234,Female,80.0,1,0,Yes,Private,Urban,83.75,NaN,never smoked,0
5106,44873,Female,81.0,0,0,Yes,Self-employed,Urban,125.20,40.0,never smoked,0
5107,19723,Female,35.0,0,0,Yes,Self-employed,Rural,82.99,30.6,never smoked,0
5108,37544,Male,51.0,0,0,Yes,Private,Rural,166.29,25.6,formerly smoked,0
5109,44679,Female,44.0,0,0,Yes,Govt_job,Urban,85.28,26.2,Unknown,0

In [9]:
data.shape

(5110, 12)

In [10]:
data.columns

Index(['id', 'gender', 'age', 'hypertension', 'heart_disease', 'ever_married',
       'work_type', 'Residence_type', 'avg_glucose_level', 'bmi',
       'smoking_status', 'stroke'],
      dtype='str')

In [11]:
type(data)

pandas.DataFrame

In [12]:
data_dict = data.to_dict(orient="records")

In [13]:
data_dict

[{'id': 9046,
  'gender': 'Male',
  'age': 67.0,
  'hypertension': 0,
  'heart_disease': 1,
  'ever_married': 'Yes',
  'work_type': 'Private',
  'Residence_type': 'Urban',
  'avg_glucose_level': 228.69,
  'bmi': 36.6,
  'smoking_status': 'formerly smoked',
  'stroke': 1},
 {'id': 51676,
  'gender': 'Female',
  'age': 61.0,
  'hypertension': 0,
  'heart_disease': 0,
  'ever_married': 'Yes',
  'work_type': 'Self-employed',
  'Residence_type': 'Rural',
  'avg_glucose_level': 202.21,
  'bmi': nan,
  'smoking_status': 'never smoked',
  'stroke': 1},
 {'id': 31112,
  'gender': 'Male',
  'age': 80.0,
  'hypertension': 0,
  'heart_disease': 1,
  'ever_married': 'Yes',
  'work_type': 'Private',
  'Residence_type': 'Rural',
  'avg_glucose_level': 105.92,
  'bmi': 32.5,
  'smoking_status': 'never smoked',
  'stroke': 1},
 {'id': 60182,
  'gender': 'Female',
  'age': 49.0,
  'hypertension': 0,
  'heart_disease': 0,
  'ever_married': 'Yes',
  'work_type': 'Private',
  'Residence_type': 'Urban',
  'avg_glucose_level': 171.23,
  'bmi': 34.4,
  'smoking_status': 'smokes',
  'stroke': 1},
 {'id': 1665,
  'gender': 'Female',
  'age': 79.0,
  'hypertension': 1,
  'heart_disease': 0,
  'ever_married': 'Yes',
  'work_type': 'Self-employed',
  'Residence_type': 'Rural',
  'avg_glucose_level': 174.12,
  'bmi': 24.0,
  'smoking_status': 'never smoked',
  'stroke': 1},
 {'id': 56669,
  'gender': 'Male',
  'age': 81.0,
  'hypertension': 0,
  'heart_disease': 0,
  'ever_married': 'Yes',
  'work_type': 'Private',
  'Residence_type': 'Urban',
  'avg_glucose_level': 186.21,
  'bmi': 29.0,
  'smoking_status': 'formerly smoked',
  'stroke': 1},
 {'id': 53882,
  'gender': 'Male',
  'age': 74.0,
  'hypertension': 1,
  'heart_disease': 1,
  'ever_married': 'Yes',
  'work_type': 'Private',
  'Residence_type': 'Rural',
  'avg_glucose_level': 70.09,
  'bmi': 27.4,
  'smoking_status': 'never smoked',
  'stroke': 1},
 {'id': 10434,
  'gender': 'Female',
  'age': 69.0,
  'hypertension': 0,
  'heart_disease': 0,
  'ever_married': 'No',
  'work_type': 'Private',
  'Residence_type': 'Urban',
  'avg_glucose_level': 94.39,
  'bmi': 22.8,
  'smoking_status': 'never smoked',
  'stroke': 1},
 {'id': 27419,
  'gender': 'Female',
  'age': 59.0,
  'hypertension': 0,
  'heart_disease': 0,
  'ever_married': 'Yes',
  'work_type': 'Private',
  'Residence_type': 'Rural',
  'avg_glucose_level': 76.15,
  'bmi': nan,
  'smoking_status': 'Unknown',
  'stroke': 1},
 {'id': 60491,
  'gender': 'Female',
  'age': 78.0,
  'hypertension': 0,
  'heart_disease': 0,
  'ever_married': 'Yes',
  'work_type': 'Private',
  'Residence_type': 'Urban',
  'avg_glucose_level': 58.57,
  'bmi': 24.2,
  'smoking_status': 'Unknown',
  'stroke': 1},
 {'id': 12109,
  'gender': 'Female',
  'age': 81.0,
  'hypertension': 1,
  'heart_disease': 0,
  'ever_married': 'Yes',
  'work_type': 'Private',
  'Residence_type': 'Rural',
  'avg_glucose_level': 80.43,
  'bmi': 29.7,
  'smoking_status': 'never smoked',
  'stroke': 1},
 {'id': 12095,
  'gender': 'Female',
  'age': 61.0,
  'hypertension': 0,
  'heart_disease': 1,
  'ever_married': 'Yes',
  'work_type': 'Govt_job',
  'Residence_type': 'Rural',
  'avg_glucose_level': 120.46,
  'bmi': 36.8,
  'smoking_status': 'smokes',
  'stroke': 1},
 {'id': 12175,
  'gender': 'Female',
  'age': 54.0,
  'hypertension': 0,
  'heart_disease': 0,
  'ever_married': 'Yes',
  'work_type': 'Private',
  'Residence_type': 'Urban',
  'avg_glucose_level': 104.51,
  'bmi': 27.3,
  'smoking_status': 'smokes',
  'stroke': 1},
 {'id': 8213,
  'gender': 'Male',
  'age': 78.0,
  'hypertension': 0,
  'heart_disease': 1,
  'ever_married': 'Yes',
  'work_type': 'Private',
  'Residence_type': 'Urban',
  'avg_glucose_level': 219.84,
  'bmi': nan,
  'smoking_status': 'Unknown',
  'stroke': 1},
 {'id': 5317,
  'gender': 'Female',
  'age': 79.0,
  'hypertension': 0,
  'heart_disease': 1,
  'ever_married': 'Yes',
  'work_type': 'Private',
  'Residence_type': 'Urban',
  'avg_glucose_level': 214.09,
  'bmi': 28.2,
  'smoking_status': 'never smoked',
  'stroke': 1},
 {'id': 58202,
  'gender': 'Female',
  'age': 50.0,
  'hypertension': 1,
  'heart_disease': 0,
  'ever_married': 'Yes',
  'work_type': 'Self-employed',
  'Residence_type': 'Rural',
  'avg_glucose_level': 167.41,
  'bmi': 30.9,
  'smoking_status': 'never smoked',
  'stroke': 1},
 {'id': 56112,
  'gender': 'Male',
  'age': 64.0,
  'hypertension': 0,
  'heart_disease': 1,
  'ever_married': 'Yes',
  'work_type': 'Private',
  'Residence_type': 'Urban',
  'avg_glucose_level': 191.61,
  'bmi': 37.5,
  'smoking_status': 'smokes',
  'stroke': 1},
 {'id': 34120,
  'gender': 'Male',
  'age': 75.0,
  'hypertension': 1,
  'heart_disease': 0,
  'ever_married': 'Yes',
  'work_type': 'Private',
  'Residence_type': 'Urban',
  'avg_glucose_level': 221.29,
  'bmi': 25.8,
  'smoking_status': 'smokes',
  'stroke': 1},
 {'id': 27458,
  'gender': 'Female',
  'age': 60.0,
  'hypertension': 0,
  'heart_disease': 0,
  'ever_married': 'No',
  'work_type': 'Private',
  'Residence_type': 'Urban',
  'avg_glucose_level': 89.22,
  'bmi': 37.8,
  'smoking_status': 'never smoked',
  'stroke': 1},
 {'id': 25226,
  'gender': 'Male',
  'age': 57.0,
  'hypertension': 0,
  'heart_disease': 1,
  'ever_married': 'No',
  'work_type': 'Govt_job',
  'Residence_type': 'Urban',
  'avg_glucose_level': 217.08,
  'bmi': nan,
  'smoking_status': 'Unknown',
  'stroke': 1},
 {'id': 70630,
  'gender': 'Female',
  'age': 71.0,
  'hypertension': 0,
  'heart_disease': 0,
  'ever_married': 'Yes',
  'work_type': 'Govt_job',
  'Residence_type': 'Rural',
  'avg_glucose_level': 193.94,
  'bmi': 22.4,
  'smoking_status': 'smokes',
  'stroke': 1},
 {'id': 13861,
  'gender': 'Female',
  'age': 52.0,
  'hypertension': 1,
  'heart_disease': 0,
  'ever_married': 'Yes',
  'work_type': 'Self-employed',
  'Residence_type': 'Urban',
  'avg_glucose_level': 233.29,
  'bmi': 48.9,
  'smoking_status': 'never smoked',
  'stroke': 1},
 {'id': 68794,
  'gender': 'Female',
  'age': 79.0,
  'hypertension': 0,
  'heart_disease': 0,
  'ever_married': 'Yes',
  'work_type': 'Self-employed',
  'Residence_type': 'Urban',
  'avg_glucose_level': 228.7,
  'bmi': 26.6,
  'smoking_status': 'never smoked',
  'stroke': 1},
 {'id': 64778,
  'gender': 'Male',
  'age': 82.0,
  'hypertension': 0,
  'heart_disease': 1,
  'ever_married': 'Yes',
  'work_type': 'Private',
  'Residence_type': 'Rural',
  'avg_glucose_level': 208.3,
  'bmi': 32.5,
  'smoking_status': 'Unknown',
  'stroke': 1},
 {'id': 4219,
  'gender': 'Male',
  'age': 71.0,
  'hypertension': 0,
  'heart_disease': 0,
  'ever_married': 'Yes',
  'work_type': 'Private',
  'Residence_type': 'Urban',
  'avg_glucose_level': 102.87,
  'bmi': 27.2,
  'smoking_status': 'formerly smoked',
  'stroke': 1},
 {'id': 70822,
  'gender': 'Male',
  'age': 80.0,
  'hypertension': 0,
  'heart_disease': 0,
  'ever_married': 'Yes',
  'work_type': 'Self-employed',
  'Residence_type': 'Rural',
  'avg_glucose_level': 104.12,
  'bmi': 23.5,
  'smoking_status': 'never smoked',
  'stroke': 1},
 {'id': 38047,
  'gender': 'Female',
  'age': 65.0,
  'hypertension': 0,
  'heart_disease': 0,
  'ever_married': 'Yes',
  'work_type': 'Private',
  'Residence_type': 'Rural',
  'avg_glucose_level': 100.98,
  'bmi': 28.2,
  'smoking_status': 'formerly smoked',
  'stroke': 1},
 {'id': 61843,
  'gender': 'Male',
  'age': 58.0,
  'hypertension': 0,
  'heart_disease': 0,
  'ever_married': 'Yes',
  'work_type': 'Private',
  'Residence_type': 'Rural',
  'avg_glucose_level': 189.84,
  'bmi': nan,
  'smoking_status': 'Unknown',
  'stroke': 1},
 {'id': 54827,
  'gender': 'Male',
  'age': 69.0,
  'hypertension': 0,
  'heart_disease': 1,
  'ever_married': 'Yes',
  'work_type': 'Self-employed',
  'Residence_type': 'Urban',
  'avg_glucose_level': 195.23,
  'bmi': 28.3,
  'smoking_status': 'smokes',
  'stroke': 1},
 {'id': 69160,
  'gender': 'Male',
  'age': 59.0,
  'hypertension': 0,
  'heart_disease': 0,
  'ever_married': 'Yes',
  'work_type': 'Private',
  'Residence_type': 'Rural',
  'avg_glucose_level': 211.78,
  'bmi': nan,
  'smoking_status': 'formerly smoked',
  'stroke': 1},
 {'id': 43717,
  'gender': 'Male',
  'age': 57.0,
  'hypertension': 1,
  'heart_disease': 0,
  'ever_married': 'Yes',
  'work_type': 'Private',
  'Residence_type': 'Urban',
  'avg_glucose_level': 212.08,
  'bmi': 44.2,
  'smoking_status': 'smokes',
  'stroke': 1},
 {'id': 33879,
  'gender': 'Male',
  'age': 42.0,
  'hypertension': 0,
  'heart_disease': 0,
  'ever_married': 'Yes',
  'work_type': 'Private',
  'Residence_type': 'Rural',
  'avg_glucose_level': 83.41,
  'bmi': 25.4,
  'smoking_status': 'Unknown',
  'stroke': 1},
 {'id': 39373,
  'gender': 'Female',
  'age': 82.0,
  'hypertension': 1,
  'heart_disease': 0,
  'ever_married': 'Yes',
  'work_type': 'Self-employed',
  'Residence_type': 'Urban',
  'avg_glucose_level': 196.92,
  'bmi': 22.2,
  'smoking_status': 'never smoked',
  'stroke': 1},
 {'id': 54401,
  'gender': 'Male',
  'age': 80.0,
  'hypertension': 0,
  'heart_disease': 1,
  'ever_married': 'Yes',
  'work_type': 'Self-employed',
  'Residence_type': 'Urban',
  'avg_glucose_level': 252.72,
  'bmi': 30.5,
  'smoking_status': 'formerly smoked',
  'stroke': 1},
 {'id': 14248,
  'gender': 'Male',
  'age': 48.0,
  'hypertension': 0,
  'heart_disease': 0,
  'ever_married': 'No',
  'work_type': 'Govt_job',
  'Residence_type': 'Urban',
  'avg_glucose_level': 84.2,
  'bmi': 29.7,
  'smoking_status': 'never smoked',
  'stroke': 1},
 {'id': 712,
  'gender': 'Female',
  'age': 82.0,
  'hypertension': 1,
  'heart_disease': 1,
  'ever_married': 'No',
  'work_type': 'Private',
  'Residence_type': 'Rural',
  'avg_glucose_level': 84.03,
  'bmi': 26.5,
  'smoking_status': 'formerly smoked',
  'stroke': 1},
 {'id': 47269,
  'gender': 'Male',
  'age': 74.0,
  'hypertension': 0,
  'heart_disease': 0,
  'ever_married': 'Yes',
  'work_type': 'Private',
  'Residence_type': 'Rural',
  'avg_glucose_level': 219.72,
  'bmi': 33.7,
  'smoking_status': 'formerly smoked',
  'stroke': 1},
 {'id': 24977,
  'gender': 'Female',
  'age': 72.0,
  'hypertension': 1,
  'heart_disease': 0,
  'ever_married': 'Yes',
  'work_type': 'Private',
  'Residence_type': 'Rural',
  'avg_glucose_level': 74.63,
  'bmi': 23.1,
  'smoking_status': 'formerly smoked',
  'stroke': 1},
 {'id': 47306,
  'gender': 'Male',
  'age': 58.0,
  'hypertension': 0,
  'heart_disease': 0,
  'ever_married': 'No',
  'work_type': 'Private',
  'Residence_type': 'Rural',
  'avg_glucose_level': 92.62,
  'bmi': 32.0,
  'smoking_status': 'Unknown',
  'stroke': 1},
 {'id': 62602,
  'gender': 'Female',
  'age': 49.0,
  'hypertension': 0,
  'heart_disease': 0,
  'ever_married': 'Yes',
  'work_type': 'Private',
  'Residence_type': 'Urban',
  'avg_glucose_level': 60.91,
  'bmi': 29.9,
  'smoking_status': 'never smoked',
  'stroke': 1},
 {'id': 4651,
  'gender': 'Male',
  'age': 78.0,
  'hypertension': 0,
  'heart_disease': 0,
  'ever_married': 'Yes',
  'work_type': 'Private',
  'Residence_type': 'Rural',
  'avg_glucose_level': 78.03,
  'bmi': 23.9,
  'smoking_status': 'formerly smoked',
  'stroke': 1},
 {'id': 1261,
  'gender': 'Male',
  'age': 54.0,
  'hypertension': 0,
  'heart_disease': 0,
  'ever_married': 'Yes',
  'work_type': 'Private',
  'Residence_type': 'Urban',
  'avg_glucose_level': 71.22,
  'bmi': 28.5,
  'smoking_status': 'never smoked',
  'stroke': 1},
 {'id': 61960,
  'gender': 'Male',
  'age': 82.0,
  'hypertension': 0,
  'heart_disease': 1,
  'ever_married': 'Yes',
  'work_type': 'Private',
  'Residence_type': 'Urban',
  'avg_glucose_level': 144.9,
  'bmi': 26.4,
  'smoking_status': 'smokes',
  'stroke': 1},
 {'id': 1845,
  'gender': 'Female',
  'age': 63.0,
  'hypertension': 0,
  'heart_disease': 0,
  'ever_married': 'Yes',
  'work_type': 'Private',
  'Residence_type': 'Urban',
  'avg_glucose_level': 90.9,
  'bmi': nan,
  'smoking_status': 'formerly smoked',
  'stroke': 1},
 {'id': 7937,
  'gender': 'Male',
  'age': 60.0,
  'hypertension': 1,
  'heart_disease': 0,
  'ever_married': 'Yes',
  'work_type': 'Govt_job',
  'Residence_type': 'Urban',
  'avg_glucose_level': 213.03,
  'bmi': 20.2,
  'smoking_status': 'smokes',
  'stroke': 1},
 {'id': 19824,
  'gender': 'Male',
  'age': 76.0,
  'hypertension': 1,
  'heart_disease': 0,
  'ever_married': 'Yes',
  'work_type': 'Private',
  'Residence_type': 'Rural',
  'avg_glucose_level': 243.58,
  'bmi': 33.6,
  'smoking_status': 'never smoked',
  'stroke': 1},
 {'id': 37937,
  'gender': 'Female',
  'age': 75.0,
  'hypertension': 0,
  'heart_disease': 1,
  'ever_married': 'No',
  'work_type': 'Self-employed',
  'Residence_type': 'Urban',
  'avg_glucose_level': 109.78,
  'bmi': nan,
  'smoking_status': 'Unknown',
  'stroke': 1},
 {'id': 47472,
  'gender': 'Female',
  'age': 58.0,
  'hypertension': 0,
  'heart_disease': 0,
  'ever_married': 'Yes',
  'work_type': 'Private',
  'Residence_type': 'Urban',
  'avg_glucose_level': 107.26,
  'bmi': 38.6,
  'smoking_status': 'formerly smoked',
  'stroke': 1},
 {'id': 35626,
  'gender': 'Male',
  'age': 81.0,
  'hypertension': 0,
  'heart_disease': 0,
  'ever_married': 'Yes',
  'work_type': 'Self-employed',
  'Residence_type': 'Urban',
  'avg_glucose_level': 99.33,
  'bmi': 33.7,
  'smoking_status': 'never smoked',
  'stroke': 1},
 {'id': 36338,
  'gender': 'Female',
  'age': 39.0,
  'hypertension': 1,
  'heart_disease': 0,
  'ever_married': 'Yes',
  'work_type': 'Private',
  'Residence_type': 'Rural',
  'avg_glucose_level': 58.09,
  'bmi': 39.2,
  'smoking_status': 'smokes',
  'stroke': 1},
 {'id': 18587,
  'gender': 'Female',
  'age': 76.0,
  'hypertension': 0,
  'heart_disease': 0,
  'ever_married': 'No',
  'work_type': 'Private',
  'Residence_type': 'Urban',
  'avg_glucose_level': 89.96,
  'bmi': nan,
  'smoking_status': 'Unknown',
  'stroke': 1},
 {'id': 15102,
  'gender': 'Male',
  'age': 78.0,
  'hypertension': 1,
  'heart_disease': 0,
  'ever_married': 'Yes',
  'work_type': 'Private',
  'Residence_type': 'Urban',
  'avg_glucose_level': 75.32,
  'bmi': nan,
  'smoking_status': 'formerly smoked',
  'stroke': 1},
 {'id': 59190,
  'gender': 'Female',
  'age': 79.0,
  'hypertension': 0,
  'heart_disease': 1,
  'ever_married': 'Yes',
  'work_type': 'Private',
  'Residence_type': 'Rural',
  'avg_glucose_level': 127.29,
  'bmi': 27.7,
  'smoking_status': 'never smoked',
  'stroke': 1},
 {'id': 47167,
  'gender': 'Female',
  'age': 77.0,
  'hypertension': 1,
  'heart_disease': 0,
  'ever_married': 'Yes',
  'work_type': 'Self-employed',
  'Residence_type': 'Urban',
  'avg_glucose_level': 124.13,
  'bmi': 31.4,
  'smoking_status': 'never smoked',
  'stroke': 1},
 {'id': 8752,
  'gender': 'Female',
  'age': 63.0,
  'hypertension': 0,
  'heart_disease': 0,
  'ever_married': 'Yes',
  'work_type': 'Govt_job',
  'Residence_type': 'Urban',
  'avg_glucose_level': 197.54,
  'bmi': nan,
  'smoking_status': 'never smoked',
  'stroke': 1},
 {'id': 25831,
  'gender': 'Male',
  'age': 63.0,
  'hypertension': 0,
  'heart_disease': 1,
  'ever_married': 'Yes',
  'work_type': 'Private',
  'Residence_type': 'Rural',
  'avg_glucose_level': 196.71,
  'bmi': 36.5,
  'smoking_status': 'formerly smoked',
  'stroke': 1},
 {'id': 38829,
  'gender': 'Female',
  'age': 82.0,
  'hypertension': 0,
  'heart_disease': 0,
  'ever_married': 'Yes',
  'work_type': 'Private',
  'Residence_type': 'Rural',
  'avg_glucose_level': 59.32,
  'bmi': 33.2,
  'smoking_status': 'never smoked',
  'stroke': 1},
 {'id': 66400,
  'gender': 'Male',
  'age': 78.0,
  'hypertension': 0,
  'heart_disease': 0,
  'ever_married': 'Yes',
  'work_type': 'Private',
  'Residence_type': 'Urban',
  'avg_glucose_level': 237.75,
  'bmi': nan,
  'smoking_status': 'formerly smoked',
  'stroke': 1},
 {'id': 58631,
  'gender': 'Male',
  'age': 73.0,
  'hypertension': 1,
  'heart_disease': 0,
  'ever_married': 'Yes',
  'work_type': 'Self-employed',
  'Residence_type': 'Urban',
  'avg_glucose_level': 194.99,
  'bmi': 32.8,
  'smoking_status': 'never smoked',
  'stroke': 1},
 {'id': 5111,
  'gender': 'Female',
  'age': 54.0,
  'hypertension': 1,
  'heart_disease': 0,
  'ever_married': 'Yes',
  'work_type': 'Govt_job',
  'Residence_type': 'Urban',
  'avg_glucose_level': 180.93,
  'bmi': 27.7,
  'smoking_status': 'never smoked',
  'stroke': 1},
 {'id': 10710,
  'gender': 'Female',
  'age': 56.0,
  'hypertension': 0,
  'heart_disease': 0,
  'ever_married': 'Yes',
  'work_type': 'Private',
  'Residence_type': 'Urban',
  'avg_glucose_level': 185.17,
  'bmi': 40.4,
  'smoking_status': 'formerly smoked',
  'stroke': 1},
 {'id': 55927,
  'gender': 'Female',
  'age': 80.0,
  'hypertension': 1,
  'heart_disease': 0,
  'ever_married': 'Yes',
  'work_type': 'Private',
  'Residence_type': 'Rural',
  'avg_glucose_level': 74.9,
  'bmi': 22.2,
  'smoking_status': 'never smoked',
  'stroke': 1},
 {'id': 65842,
  'gender': 'Female',
  'age': 67.0,
  'hypertension': 1,
  'heart_disease': 0,
  'ever_married': 'Yes',
  'work_type': 'Self-employed',
  'Residence_type': 'Rural',
  'avg_glucose_level': 61.94,
  'bmi': 25.3,
  'smoking_status': 'smokes',
  'stroke': 1},
 {'id': 19557,
  'gender': 'Female',
  'age': 45.0,
  'hypertension': 0,
  'heart_disease': 0,
  'ever_married': 'Yes',
  'work_type': 'Private',
  'Residence_type': 'Rural',
  'avg_glucose_level': 93.72,
  'bmi': 30.2,
  'smoking_status': 'formerly smoked',
  'stroke': 1},
 {'id': 7356,
  'gender': 'Male',
  'age': 75.0,
  'hypertension': 0,
  'heart_disease': 0,
  'ever_married': 'Yes',
  'work_type': 'Private',
  'Residence_type': 'Urban',
  'avg_glucose_level': 104.72,
  'bmi': nan,
  'smoking_status': 'Unknown',
  'stroke': 1},
 {'id': 17013,
  'gender': 'Male',
  'age': 78.0,
  'hypertension': 1,
  'heart_disease': 0,
  'ever_married': 'No',
  'work_type': 'Private',
  'Residence_type': 'Urban',
  'avg_glucose_level': 113.01,
  'bmi': 24.0,
  'smoking_status': 'never smoked',
  'stroke': 1},
 {'id': 17004,
  'gender': 'Female',
  'age': 70.0,
  'hypertension': 0,
  'heart_disease': 0,
  'ever_married': 'Yes',
  'work_type': 'Private',
  'Residence_type': 'Urban',
  'avg_glucose_level': 221.58,
  'bmi': 47.5,
  'smoking_status': 'never smoked',
  'stroke': 1},
 {'id': 72366,
  'gender': 'Male',
  'age': 76.0,
  'hypertension': 0,
  'heart_disease': 0,
  'ever_married': 'Yes',
  'work_type': 'Private',
  'Residence_type': 'Urban',
  'avg_glucose_level': 104.47,
  'bmi': 20.3,
  'smoking_status': 'Unknown',
  'stroke': 1},
 {'id': 6118,
  'gender': 'Male',
  'age': 59.0,
  'hypertension': 0,
  'heart_disease': 0,
  'ever_married': 'Yes',
  'work_type': 'Private',
  'Residence_type': 'Urban',
  'avg_glucose_level': 86.23,
  'bmi': 30.0,
  'smoking_status': 'formerly smoked',
  'stroke': 1},
 {'id': 7371,
  'gender': 'Female',
  'age': 80.0,
  'hypertension': 1,
  'heart_disease': 0,
  'ever_married': 'Yes',
  'work_type': 'Self-employed',
  'Residence_type': 'Rural',
  'avg_glucose_level': 72.67,
  'bmi': 28.9,
  'smoking_status': 'never smoked',
  'stroke': 1},
 {'id': 70676,
  'gender': 'Female',
  'age': 76.0,
  'hypertension': 0,
  'heart_disease': 0,
  'ever_married': 'Yes',
  'work_type': 'Govt_job',
  'Residence_type': 'Rural',
  'avg_glucose_level': 62.57,
  'bmi': nan,
  'smoking_status': 'formerly smoked',
  'stroke': 1},
 {'id': 2326,
  'gender': 'Female',
  'age': 67.0,
  'hypertension': 1,
  'heart_disease': 0,
  'ever_married': 'Yes',
  'work_type': 'Private',
  'Residence_type': 'Rural',
  'avg_glucose_level': 179.12,
  'bmi': 28.1,
  'smoking_status': 'formerly smoked',
  'stroke': 1},
 {'id': 27169,
  'gender': 'Female',
  'age': 66.0,
  'hypertension': 1,
  'heart_disease': 0,
  'ever_married': 'Yes',
  'work_type': 'Govt_job',
  'Residence_type': 'Rural',
  'avg_glucose_level': 116.55,
  'bmi': 31.1,
  'smoking_status': 'formerly smoked',
  'stroke': 1},
 {'id': 50784,
  'gender': 'Male',
  'age': 63.0,
  'hypertension': 0,
  'heart_disease': 0,
  'ever_married': 'Yes',
  'work_type': 'Private',
  'Residence_type': 'Rural',

In [14]:
len(data_dict)

5110

In [17]:
DB_NAME = "my_database"
COLLECTION_NAME = "my_collection"
COLLECTION_URL = "mongodb+srv://navinxqz:%23Navin%40477@cluster0.am2sy53.mongodb.net/?appName=Cluster0"

In [18]:
import pymongo
client = pymongo.MongoClient(COLLECTION_URL)
db_base = client[DB_NAME]
collection = db_base[COLLECTION_NAME]

### Storing Data to MongoDB

In [19]:
# data push to mongodb
rec=collection.insert_many(data_dict)

### Fetching Data from MongoDB

In [20]:
records=collection.find()

In [21]:
records

In [22]:
for i in records:
    print(i)

{'_id': ObjectId('69a493cbc741e7cfea0a3eba'), 'id': 9046, 'gender': 'Male', 'age': 67.0, 'hypertension': 0, 'heart_disease': 1, 'ever_married': 'Yes', 'work_type': 'Private', 'Residence_type': 'Urban', 'avg_glucose_level': 228.69, 'bmi': 36.6, 'smoking_status': 'formerly smoked', 'stroke': 1}
{'_id': ObjectId('69a493cbc741e7cfea0a3ebb'), 'id': 51676, 'gender': 'Female', 'age': 61.0, 'hypertension': 0, 'heart_disease': 0, 'ever_married': 'Yes', 'work_type': 'Self-employed', 'Residence_type': 'Rural', 'avg_glucose_level': 202.21, 'bmi': nan, 'smoking_status': 'never smoked', 'stroke': 1}
{'_id': ObjectId('69a493cbc741e7cfea0a3ebc'), 'id': 31112, 'gender': 'Male', 'age': 80.0, 'hypertension': 0, 'heart_disease': 1, 'ever_married': 'Yes', 'work_type': 'Private', 'Residence_type': 'Rural', 'avg_glucose_level': 105.92, 'bmi': 32.5, 'smoking_status': 'never smoked', 'stroke': 1}
{'_id': ObjectId('69a493cbc741e7cfea0a3ebd'), 'id': 60182, 'gender': 'Female', 'age': 49.0, 'hypertension': 0, 'heart_disease': 0, 'ever_married': 'Yes', 'work_type': 'Private', 'Residence_type': 'Urban', 'avg_glucose_level': 171.23, 'bmi': 34.4, 'smoking_status': 'smokes', 'stroke': 1}
{'_id': ObjectId('69a493cbc741e7cfea0a3ebe'), 'id': 1665, 'gender': 'Female', 'age': 79.0, 'hypertension': 1, 'heart_disease': 0, 'ever_married': 'Yes', 'work_type': 'Self-employed', 'Residence_type': 'Rural', 'avg_glucose_level': 174.12, 'bmi': 24.0, 'smoking_status': 'never smoked', 'stroke': 1}
{'_id': ObjectId('69a493cbc741e7cfea0a3ebf'), 'id': 56669, 'gender': 'Male', 'age': 81.0, 'hypertension': 0, 'heart_disease': 0, 'ever_married': 'Yes', 'work_type': 'Private', 'Residence_type': 'Urban', 'avg_glucose_level': 186.21, 'bmi': 29.0, 'smoking_status': 'formerly smoked', 'stroke': 1}
{'_id': ObjectId('69a493cbc741e7cfea0a3ec0'), 'id': 53882, 'gender': 'Male', 'age': 74.0, 'hypertension': 1, 'heart_disease': 1, 'ever_married': 'Yes', 'work_type': 'Private', 'Residence_type': 'Rural', 'avg_glucose_level': 70.09, 'bmi': 27.4, 'smoking_status': 'never smoked', 'stroke': 1}
{'_id': ObjectId('69a493cbc741e7cfea0a3ec1'), 'id': 10434, 'gender': 'Female', 'age': 69.0, 'hypertension': 0, 'heart_disease': 0, 'ever_married': 'No', 'work_type': 'Private', 'Residence_type': 'Urban', 'avg_glucose_level': 94.39, 'bmi': 22.8, 'smoking_status': 'never smoked', 'stroke': 1}
{'_id': ObjectId('69a493cbc741e7cfea0a3ec2'), 'id': 27419, 'gender': 'Female', 'age': 59.0, 'hypertension': 0, 'heart_disease': 0, 'ever_married': 'Yes', 'work_type': 'Private', 'Residence_type': 'Rural', 'avg_glucose_level': 76.15, 'bmi': nan, 'smoking_status': 'Unknown', 'stroke': 1}
{'_id': ObjectId('69a493cbc741e7cfea0a3ec3'), 'id': 60491, 'gender': 'Female', 'age': 78.0, 'hypertension': 0, 'heart_disease': 0, 'ever_married': 'Yes', 'work_type': 'Private', 'Residence_type': 'Urban', 'avg_glucose_level': 58.57, 'bmi': 24.2, 'smoking_status': 'Unknown', 'stroke': 1}
{'_id': ObjectId('69a493cbc741e7cfea0a3ec4'), 'id': 12109, 'gender': 'Female', 'age': 81.0, 'hypertension': 1, 'heart_disease': 0, 'ever_married': 'Yes', 'work_type': 'Private', 'Residence_type': 'Rural', 'avg_glucose_level': 80.43, 'bmi': 29.7, 'smoking_status': 'never smoked', 'stroke': 1}
{'_id': ObjectId('69a493cbc741e7cfea0a3ec5'), 'id': 12095, 'gender': 'Female', 'age': 61.0, 'hypertension': 0, 'heart_disease': 1, 'ever_married': 'Yes', 'work_type': 'Govt_job', 'Residence_type': 'Rural', 'avg_glucose_level': 120.46, 'bmi': 36.8, 'smoking_status': 'smokes', 'stroke': 1}
{'_id': ObjectId('69a493cbc741e7cfea0a3ec6'), 'id': 12175, 'gender': 'Female', 'age': 54.0, 'hypertension': 0, 'heart_disease': 0, 'ever_married': 'Yes', 'work_type': 'Private', 'Residence_type': 'Urban', 'avg_glucose_level': 104.51, 'bmi': 27.3, 'smoking_status': 'smokes', 'stroke': 1}
{'_id': ObjectId('69a493cbc741e7cfea0a3ec7'), 'id': 8213, 'gender': 'Male', 'age': 78.0, 'hypertension': 0, 'heart_disease': 1, 'ever_married': 'Yes', 'work_type': 'Private', 'Residence_type': 'Urban', 'avg_glucose_level': 219.84, 'bmi': nan, 'smoking_status': 'Unknown', 'stroke': 1}
{'_id': ObjectId('69a493cbc741e7cfea0a3ec8'), 'id': 5317, 'gender': 'Female', 'age': 79.0, 'hypertension': 0, 'heart_disease': 1, 'ever_married': 'Yes', 'work_type': 'Private', 'Residence_type': 'Urban', 'avg_glucose_level': 214.09, 'bmi': 28.2, 'smoking_status': 'never smoked', 'stroke': 1}
{'_id': ObjectId('69a493cbc741e7cfea0a3ec9'), 'id': 58202, 'gender': 'Female', 'age': 50.0, 'hypertension': 1, 'heart_disease': 0, 'ever_married': 'Yes', 'work_type': 'Self-employed', 'Residence_type': 'Rural', 'avg_glucose_level': 167.41, 'bmi': 30.9, 'smoking_status': 'never smoked', 'stroke': 1}
{'_id': ObjectId('69a493cbc741e7cfea0a3eca'), 'id': 56112, 'gender': 'Male', 'age': 64.0, 'hypertension': 0, 'heart_disease': 1, 'ever_married': 'Yes', 'work_type': 'Private', 'Residence_type': 'Urban', 'avg_glucose_level': 191.61, 'bmi': 37.5, 'smoking_status': 'smokes', 'stroke': 1}
{'_id': ObjectId('69a493cbc741e7cfea0a3ecb'), 'id': 34120, 'gender': 'Male', 'age': 75.0, 'hypertension': 1, 'heart_disease': 0, 'ever_married': 'Yes', 'work_type': 'Private', 'Residence_type': 'Urban', 'avg_glucose_level': 221.29, 'bmi': 25.8, 'smoking_status': 'smokes', 'stroke': 1}
{'_id': ObjectId('69a493cbc741e7cfea0a3ecc'), 'id': 27458, 'gender': 'Female', 'age': 60.0, 'hypertension': 0, 'heart_disease': 0, 'ever_married': 'No', 'work_type': 'Private', 'Residence_type': 'Urban', 'avg_glucose_level': 89.22, 'bmi': 37.8, 'smoking_status': 'never smoked', 'stroke': 1}
{'_id': ObjectId('69a493cbc741e7cfea0a3ecd'), 'id': 25226, 'gender': 'Male', 'age': 57.0, 'hypertension': 0, 'heart_disease': 1, 'ever_married': 'No', 'work_type': 'Govt_job', 'Residence_type': 'Urban', 'avg_glucose_level': 217.08, 'bmi': nan, 'smoking_status': 'Unknown', 'stroke': 1}
{'_id': ObjectId('69a493cbc741e7cfea0a3ece'), 'id': 70630, 'gender': 'Female', 'age': 71.0, 'hypertension': 0, 'heart_disease': 0, 'ever_married': 'Yes', 'work_type': 'Govt_job', 'Residence_type': 'Rural', 'avg_glucose_level': 193.94, 'bmi': 22.4, 'smoking_status': 'smokes', 'stroke': 1}
{'_id': ObjectId('69a493cbc741e7cfea0a3ecf'), 'id': 13861, 'gender': 'Female', 'age': 52.0, 'hypertension': 1, 'heart_disease': 0, 'ever_married': 'Yes', 'work_type': 'Self-employed', 'Residence_type': 'Urban', 'avg_glucose_level': 233.29, 'bmi': 48.9, 'smoking_status': 'never smoked', 'stroke': 1}
{'_id': ObjectId('69a493cbc741e7cfea0a3ed0'), 'id': 68794, 'gender': 'Female', 'age': 79.0, 'hypertension': 0, 'heart_disease': 0, 'ever_married': 'Yes', 'work_type': 'Self-employed', 'Residence_type': 'Urban', 'avg_glucose_level': 228.7, 'bmi': 26.6, 'smoking_status': 'never smoked', 'stroke': 1}
{'_id': ObjectId('69a493cbc741e7cfea0a3ed1'), 'id': 64778, 'gender': 'Male', 'age': 82.0, 'hypertension': 0, 'heart_disease': 1, 'ever_married': 'Yes', 'work_type': 'Private', 'Residence_type': 'Rural', 'avg_glucose_level': 208.3, 'bmi': 32.5, 'smoking_status': 'Unknown', 'stroke': 1}
{'_id': ObjectId('69a493cbc741e7cfea0a3ed2'), 'id': 4219, 'gender': 'Male', 'age': 71.0, 'hypertension': 0, 'heart_disease': 0, 'ever_married': 'Yes', 'work_type': 'Private', 'Residence_type': 'Urban', 'avg_glucose_level': 102.87, 'bmi': 27.2, 'smoking_status': 'formerly smoked', 'stroke': 1}
{'_id': ObjectId('69a493cbc741e7cfea0a3ed3'), 'id': 70822, 'gender': 'Male', 'age': 80.0, 'hypertension': 0, 'heart_disease': 0, 'ever_married': 'Yes', 'work_type': 'Self-employed', 'Residence_type': 'Rural', 'avg_glucose_level': 104.12, 'bmi': 23.5, 'smoking_status': 'never smoked', 'stroke': 1}
{'_id': ObjectId('69a493cbc741e7cfea0a3ed4'), 'id': 38047, 'gender': 'Female', 'age': 65.0, 'hypertension': 0, 'heart_disease': 0, 'ever_married': 'Yes', 'work_type': 'Private', 'Residence_type': 'Rural', 'avg_glucose_level': 100.98, 'bmi': 28.2, 'smoking_status': 'formerly smoked', 'stroke': 1}
{'_id': ObjectId('69a493cbc741e7cfea0a3ed5'), 'id': 61843, 'gender': 'Male', 'age': 58.0, 'hypertension': 0, 'heart_disease': 0, 'ever_married': 'Yes', 'work_type': 'Private', 'Residence_type': 'Rural', 'avg_glucose_level': 189.84, 'bmi': nan, 'smoking_status': 'Unknown', 'stroke': 1}
{'_id': ObjectId('69a493cbc741e7cfea0a3ed6'), 'id': 54827, 'gender': 'Male', 'age': 69.0, 'hypertension': 0, 'heart_disease': 1, 'ever_married': 'Yes', 'work_type': 'Self-employed', 'Residence_type': 'Urban', 'avg_glucose_level': 195.23, 'bmi': 28.3, 'smoking_status': 'smokes', 'stroke': 1}
{'_id': ObjectId('69a493cbc741e7cfea0a3ed7'), 'id': 69160, 'gender': 'Male', 'age': 59.0, 'hypertension': 0, 'heart_disease': 0, 'ever_married': 'Yes', 'work_type': 'Private', 'Residence_type': 'Rural', 'avg_glucose_level': 211.78, 'bmi': nan, 'smoking_status': 'formerly smoked', 'stroke': 1}
{'_id': ObjectId('69a493cbc741e7cfea0a3ed8'), 'id': 43717, 'gender': 'Male', 'age': 57.0, 'hypertension': 1, 'heart_disease': 0, 'ever_married': 'Yes', 'work_type': 'Private', 'Residence_type': 'Urban', 'avg_glucose_level': 212.08, 'bmi': 44.2, 'smoking_status': 'smokes', 'stroke': 1}
{'_id': ObjectId('69a493cbc741e7cfea0a3ed9'), 'id': 33879, 'gender': 'Male', 'age': 42.0, 'hypertension': 0, 'heart_disease': 0, 'ever_married': 'Yes', 'work_type': 'Private', 'Residence_type': 'Rural', 'avg_glucose_level': 83.41, 'bmi': 25.4, 'smoking_status': 'Unknown', 'stroke': 1}
{'_id': ObjectId('69a493cbc741e7cfea0a3eda'), 'id': 39373, 'gender': 'Female', 'age': 82.0, 'hypertension': 1, 'heart_disease': 0, 'ever_married': 'Yes', 'work_type': 'Self-employed', 'Residence_type': 'Urban', 'avg_glucose_level': 196.92, 'bmi': 22.2, 'smoking_status': 'never smoked', 'stroke': 1}
{'_id': ObjectId('69a493cbc741e7cfea0a3edb'), 'id': 54401, 'gender': 'Male', 'age': 80.0, 'hypertension': 0, 'heart_disease': 1, 'ever_married': 'Yes', 'work_type': 'Self-employed', 'Residence_type': 'Urban', 'avg_glucose_level': 252.72, 'bmi': 30.5, 'smoking_status': 'formerly smoked', 'stroke': 1}
{'_id': ObjectId('69a493cbc741e7cfea0a3edc'), 'id': 14248, 'gender': 'Male', 'age': 48.0, 'hypertension': 0, 'heart_disease': 0, 'ever_married': 'No', 'work_type': 'Govt_job', 'Residence_type': 'Urban', 'avg_glucose_level': 84.2, 'bmi': 29.7, 'smoking_status': 'never smoked', 'stroke': 1}
{'_id': ObjectId('69a493cbc741e7cfea0a3edd'), 'id': 712, 'gender': 'Female', 'age': 82.0, 'hypertension': 1, 'heart_disease': 1, 'ever_married': 'No', 'work_type': 'Private', 'Residence_type': 'Rural', 'avg_glucose_level': 84.03, 'bmi': 26.5, 'smoking_status': 'formerly smoked', 'stroke': 1}
{'_id': ObjectId('69a493cbc741e7cfea0a3ede'), 'id': 47269, 'gender': 'Male', 'age': 74.0, 'hypertension': 0, 'heart_disease': 0, 'ever_married': 'Yes', 'work_type': 'Private', 'Residence_type': 'Rural', 'avg_glucose_level': 219.72, 'bmi': 33.7, 'smoking_status': 'formerly smoked', 'stroke': 1}
{'_id': ObjectId('69a493cbc741e7cfea0a3edf'), 'id': 24977, 'gender': 'Female', 'age': 72.0, 'hypertension': 1, 'heart_disease': 0, 'ever_married': 'Yes', 'work_type': 'Private', 'Residence_type': 'Rural', 'avg_glucose_level': 74.63, 'bmi': 23.1, 'smoking_status': 'formerly smoked', 'stroke': 1}
{'_id': ObjectId('69a493cbc741e7cfea0a3ee0'), 'id': 47306, 'gender': 'Male', 'age': 58.0, 'hypertension': 0, 'heart_disease': 0, 'ever_married': 'No', 'work_type': 'Private', 'Residence_type': 'Rural', 'avg_glucose_level': 92.62, 'bmi': 32.0, 'smoking_status': 'Unknown', 'stroke': 1}
{'_id': ObjectId('69a493cbc741e7cfea0a3ee1'), 'id': 62602, 'gender': 'Female', 'age': 49.0, 'hypertension': 0, 'heart_disease': 0, 'ever_married': 'Yes', 'work_type': 'Private', 'Residence_type': 'Urban', 'avg_glucose_level': 60.91, 'bmi': 29.9, 'smoking_status': 'never smoked', 'stroke': 1}
{'_id': ObjectId('69a493cbc741e7cfea0a3ee2'), 'id': 4651, 'gender': 'Male', 'age': 78.0, 'hypertension': 0, 'heart_disease': 0, 'ever_married': 'Yes', 'work_type': 'Private', 'Residence_type': 'Rural', 'avg_glucose_level': 78.03, 'bmi': 23.9, 'smoking_status': 'formerly smoked', 'stroke': 1}
{'_id': ObjectId('69a493cbc741e7cfea0a3ee3'), 'id': 1261, 'gender': 'Male', 'age': 54.0, 'hypertension': 0, 'heart_disease': 0, 'ever_married': 'Yes', 'work_type': 'Private', 'Residence_type': 'Urban', 'avg_glucose_level': 71.22, 'bmi': 28.5, 'smoking_status': 'never smoked', 'stroke': 1}
{'_id': ObjectId('69a493cbc741e7cfea0a3ee4'), 'id': 61960, 'gender': 'Male', 'age': 82.0, 'hypertension': 0, 'heart_disease': 1, 'ever_married': 'Yes', 'work_type': 'Private', 'Residence_type': 'Urban', 'avg_glucose_level': 144.9, 'bmi': 26.4, 'smoking_status': 'smokes', 'stroke': 1}
{'_id': ObjectId('69a493cbc741e7cfea0a3ee5'), 'id': 1845, 'gender': 'Female', 'age': 63.0, 'hypertension': 0, 'heart_disease': 0, 'ever_married': 'Yes', 'work_type': 'Private', 'Residence_type': 'Urban', 'avg_glucose_level': 90.9, 'bmi': nan, 'smoking_status': 'formerly smoked', 'stroke': 1}
{'_id': ObjectId('69a493cbc741e7cfea0a3ee6'), 'id': 7937, 'gender': 'Male', 'age': 60.0, 'hypertension': 1, 'heart_disease': 0, 'ever_married': 'Yes', 'work_type': 'Govt_job', 'Residence_type': 'Urban', 'avg_glucose_level': 213.03, 'bmi': 20.2, 'smoking_status': 'smokes', 'stroke': 1}
{'_id': ObjectId('69a493cbc741e7cfea0a3ee7'), 'id': 19824, 'gender': 'Male', 'age': 76.0, 'hypertension': 1, 'heart_disease': 0, 'ever_married': 'Yes', 'work_type': 'Private', 'Residence_type': 'Rural', 'avg_glucose_level': 243.58, 'bmi': 33.6, 'smoking_status': 'never smoked', 'stroke': 1}
{'_id': ObjectId('69a493cbc741e7cfea0a3ee8'), 'id': 37937, 'gender': 'Female', 'age': 75.0, 'hypertension': 0, 'heart_disease': 1, 'ever_married': 'No', 'work_type': 'Self-employed', 'Residence_type': 'Urban', 'avg_glucose_level': 109.78, 'bmi': nan, 'smoking_status': 'Unknown', 'stroke': 1}
{'_id': ObjectId('69a493cbc741e7cfea0a3ee9'), 'id': 47472, 'gender': 'Female', 'age': 58.0, 'hypertension': 0, 'heart_disease': 0, 'ever_married': 'Yes', 'work_type': 'Private', 'Residence_type': 'Urban', 'avg_glucose_level': 107.26, 'bmi': 38.6, 'smoking_status': 'formerly smoked', 'stroke': 1}
{'_id': ObjectId('69a493cbc741e7cfea0a3eea'), 'id': 35626, 'gender': 'Male', 'age': 81.0, 'hypertension': 0, 'heart_disease': 0, 'ever_married': 'Yes', 'work_type': 'Self-employed', 'Residence_type': 'Urban', 'avg_glucose_level': 99.33, 'bmi': 33.7, 'smoking_status': 'never smoked', 'stroke': 1}
{'_id': ObjectId('69a493cbc741e7cfea0a3eeb'), 'id': 36338, 'gender': 'Female', 'age': 39.0, 'hypertension': 1, 'heart_disease': 0, 'ever_married': 'Yes', 'work_type': 'Private', 'Residence_type': 'Rural', 'avg_glucose_level': 58.09, 'bmi': 39.2, 'smoking_status': 'smokes', 'stroke': 1}
{'_id': ObjectId('69a493cbc741e7cfea0a3eec'), 'id': 18587, 'gender': 'Female', 'age': 76.0, 'hypertension': 0, 'heart_disease': 0, 'ever_married': 'No', 'work_type': 'Private', 'Residence_type': 'Urban', 'avg_glucose_level': 89.96, 'bmi': nan, 'smoking_status': 'Unknown', 'stroke': 1}
{'_id': ObjectId('69a493cbc741e7cfea0a3eed'), 'id': 15102, 'gender': 'Male', 'age': 78.0, 'hypertension': 1, 'heart_disease': 0, 'ever_married': 'Yes', 'work_type': 'Private', 'Residence_type': 'Urban', 'avg_glucose_level': 75.32, 'bmi': nan, 'smoking_status': 'formerly smoked', 'stroke': 1}
{'_id': ObjectId('69a493cbc741e7cfea0a3eee'), 'id': 59190, 'gender': 'Female', 'age': 79.0, 'hypertension': 0, 'heart_disease': 1, 'ever_married': 'Yes', 'work_type': 'Private', 'Residence_type': 'Rural', 'avg_glucose_level': 127.29, 'bmi': 27.7, 'smoking_status': 'never smoked', 'stroke': 1}
{'_id': ObjectId('69a493cbc741e7cfea0a3eef'), 'id': 47167, 'gender': 'Female', 'age': 77.0, 'hypertension': 1, 'heart_disease': 0, 'ever_married': 'Yes', 'work_type': 'Self-employed', 'Residence_type': 'Urban', 'avg_glucose_level': 124.13, 'bmi': 31.4, 'smoking_status': 'never smoked', 'stroke': 1}
{'_id': ObjectId('69a493cbc741e7cfea0a3ef0'), 'id': 8752, 'gender': 'Female', 'age': 63.0, 'hypertension': 0, 'heart_disease': 0, 'ever_married': 'Yes', 'work_type': 'Govt_job', 'Residence_type': 'Urban', 'avg_glucose_level': 197.54, 'bmi': nan, 'smoking_status': 'never smoked', 'stroke': 1}
{'_id': ObjectId('69a493cbc741e7cfea0a3ef1'), 'id': 25831, 'gender': 'Male', 'age': 63.0, 'hypertension': 0, 'heart_disease': 1, 'ever_married': 'Yes', 'work_type': 'Private', 'Residence_type': 'Rural', 'avg_glucose_level': 196.71, 'bmi': 36.5, 'smoking_status': 'formerly smoked', 'stroke': 1}
{'_id': ObjectId('69a493cbc741e7cfea0a3ef2'), 'id': 38829, 'gender': 'Female', 'age': 82.0, 'hypertension': 0, 'heart_disease': 0, 'ever_married': 'Yes', 'work_type': 'Private', 'Residence_type': 'Rural', 'avg_glucose_level': 59.32, 'bmi': 33.2, 'smoking_status': 'never smoked', 'stroke': 1}
{'_id': ObjectId('69a493cbc741e7cfea0a3ef3'), 'id': 66400, 'gender': 'Male', 'age': 78.0, 'hypertension': 0, 'heart_disease': 0, 'ever_married': 'Yes', 'work_type': 'Private', 'Residence_type': 'Urban', 'avg_glucose_level': 237.75, 'bmi': nan, 'smoking_status': 'formerly smoked', 'stroke': 1}
{'_id': ObjectId('69a493cbc741e7cfea0a3ef4'), 'id': 58631, 'gender': 'Male', 'age': 73.0, 'hypertension': 1, 'heart_disease': 0, 'ever_married': 'Yes', 'work_type': 'Self-employed', 'Residence_type': 'Urban', 'avg_glucose_level': 194.99, 'bmi': 32.8, 'smoking_status': 'never smoked', 'stroke': 1}
{'_id': ObjectId('69a493cbc741e7cfea0a3ef5'), 'id': 5111, 'gender': 'Female', 'age': 54.0, 'hypertension': 1, 'heart_disease': 0, 'ever_married': 'Yes', 'work_type': 'Govt_job', 'Residence_type': 'Urban', 'avg_glucose_level': 180.93, 'bmi': 27.7, 'smoking_status': 'never smoked', 'stroke': 1}
{'_id': ObjectId('69a493cbc741e7cfea0a3ef6'), 'id': 10710, 'gender': 'Female', 'age': 56.0, 'hypertension': 0, 'heart_disease': 0, 'ever_married': 'Yes', 'work_type': 'Private', 'Residence_type': 'Urban', 'avg_glucose_level': 185.17, 'bmi': 40.4, 'smoking_status': 'formerly smoked', 'stroke': 1}
{'_id': ObjectId('69a493cbc741e7cfea0a3ef7'), 'id': 55927, 'gender': 'Female', 'age': 80.0, 'hypertension': 1, 'heart_disease': 0, 'ever_married': 'Yes', 'work_type': 'Private', 'Residence_type': 'Rural', 'avg_glucose_level': 74.9, 'bmi': 22.2, 'smoking_status': 'never smoked', 'stroke': 1}
{'_id': ObjectId('69a493cbc741e7cfea0a3ef8'), 'id': 65842, 'gender': 'Female', 'age': 67.0, 'hypertension': 1, 'heart_disease': 0, 'ever_married': 'Yes', 'work_type': 'Self-employed', 'Residence_type': 'Rural', 'avg_glucose_level': 61.94, 'bmi': 25.3, 'smoking_status': 'smokes', 'stroke': 1}
{'_id': ObjectId('69a493cbc741e7cfea0a3ef9'), 'id': 19557, 'gender': 'Female', 'age': 45.0, 'hypertension': 0, 'heart_disease': 0, 'ever_married': 'Yes', 'work_type': 'Private', 'Residence_type': 'Rural', 'avg_glucose_level': 93.72, 'bmi': 30.2, 'smoking_status': 'formerly smoked', 'stroke': 1}
{'_id': ObjectId('69a493cbc741e7cfea0a3efa'), 'id': 7356, 'gender': 'Male', 'age': 75.0, 'hypertension': 0, 'heart_disease': 0, 'ever_married': 'Yes', 'work_type': 'Private', 'Residence_type': 'Urban', 'avg_glucose_level': 104.72, 'bmi': nan, 'smoking_status': 'Unknown', 'stroke': 1}
{'_id': ObjectId('69a493cbc741e7cfea0a3efb'), 'id': 17013, 'gender': 'Male', 'age': 78.0, 'hypertension': 1, 'heart_disease': 0, 'ever_married': 'No', 'work_type': 'Private', 'Residence_type': 'Urban', 'avg_glucose_level': 113.01, 'bmi': 24.0, 'smoking_status': 'never smoked', 'stroke': 1}
{'_id': ObjectId('69a493cbc741e7cfea0a3efc'), 'id': 17004, 'gender': 'Female', 'age': 70.0, 'hypertension': 0, 'heart_disease': 0, 'ever_married': 'Yes', 'work_type': 'Private', 'Residence_type': 'Urban', 'avg_glucose_level': 221.58, 'bmi': 47.5, 'smoking_status': 'never smoked', 'stroke': 1}
{'_id': ObjectId('69a493cbc741e7cfea0a3efd'), 'id': 72366, 'gender': 'Male', 'age': 76.0, 'hypertension': 0, 'heart_disease': 0, 'ever_married': 'Yes', 'work_type': 'Private', 'Residence_type': 'Urban', 'avg_glucose_level': 104.47, 'bmi': 20.3, 'smoking_status': 'Unknown', 'stroke': 1}

In [27]:
df=pd.DataFrame(list(collection.find()))

In [28]:
df.head()

,_id,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,69a493cbc741e7cfea0a3eba,9046,Male,67.0,0,1,Yes,Private,Urban,228.69,36.6,formerly smoked,1
1,69a493cbc741e7cfea0a3ebb,51676,Female,61.0,0,0,Yes,Self-employed,Rural,202.21,NaN,never smoked,1
2,69a493cbc741e7cfea0a3ebc,31112,Male,80.0,0,1,Yes,Private,Rural,105.92,32.5,never smoked,1
3,69a493cbc741e7cfea0a3ebd,60182,Female,49.0,0,0,Yes,Private,Urban,171.23,34.4,smokes,1
4,69a493cbc741e7cfea0a3ebe,1665,Female,79.0,1,0,Yes,Self-employed,Rural,174.12,24.0,never smoked,1

In [29]:
if "_id" in df.columns.tolist():
    df.drop(columns=["_id"], inplace=True)

In [30]:
df.head()

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,9046,Male,67.0,0,1,Yes,Private,Urban,228.69,36.6,formerly smoked,1
1,51676,Female,61.0,0,0,Yes,Self-employed,Rural,202.21,NaN,never smoked,1
2,31112,Male,80.0,0,1,Yes,Private,Rural,105.92,32.5,never smoked,1
3,60182,Female,49.0,0,0,Yes,Private,Urban,171.23,34.4,smokes,1
4,1665,Female,79.0,1,0,Yes,Self-employed,Rural,174.12,24.0,never smoked,1

In [31]:
df.to_csv("D:\\Inception FSDS\\Inception-FSDS-classwork\\classwork\\Day26_Database\\healthcare-dataset-stroke-data_from_mongodb.csv", index=False)

### Database remove

In [ ]:
client.drop_database(DB_NAME)