In [1]:
import pandas as pd

In [ ]:
# [[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]] 
# raw format hard to read

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15]]

In [9]:
df= pd.DataFrame([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]], columns=['A','B','C'], index=['row1','row2','row3','row4','row5'])

In [10]:
df

       A   B   C
row1   1   2   3
row2   4   5   6
row3   7   8   9
row4  10  11  12
row5  13  14  15

In [11]:
df.head(3) # top 3 rows

      A  B  C
row1  1  2  3
row2  4  5  6
row3  7  8  9

In [12]:
df.tail(2) # bottom 2 rows

       A   B   C
row4  10  11  12
row5  13  14  15

In [13]:
df.columns # column names

Index(['A', 'B', 'C'], dtype='str')

In [15]:
df.columns.tolist() # column names in list format

['A', 'B', 'C']

In [16]:
df.index.to_list() # index names in list format

['row1', 'row2', 'row3', 'row4', 'row5']

In [17]:
df.info() # info about the dataframe

<class 'pandas.DataFrame'>
Index: 5 entries, row1 to row5
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       5 non-null      int64
 1   B       5 non-null      int64
 2   C       5 non-null      int64
dtypes: int64(3)
memory usage: 180.0 bytes

In [18]:
df.describe() # statistical summary of the dataframe

               A          B          C
count   5.000000   5.000000   5.000000
mean    7.000000   8.000000   9.000000
std     4.743416   4.743416   4.743416
min     1.000000   2.000000   3.000000
25%     4.000000   5.000000   6.000000
50%     7.000000   8.000000   9.000000
75%    10.000000  11.000000  12.000000
max    13.000000  14.000000  15.000000

In [19]:
df.nunique() # number of unique values in each column

A    5
B    5
C    5
dtype: int64

In [20]:
df["A"]

row1     1
row2     4
row3     7
row4    10
row5    13
Name: A, dtype: int64

In [17]:
df["A"].nunique() # number of unique values in column A

5

In [18]:
df["A"].unique() # unique values in column A

array([ 1,  4,  7, 10, 13])

In [19]:
df.shape # number of rows and columns in the dataframe

(5, 3)

In [20]:
df.size # number of elements in the dataframe

15

### Loading in Dataframes from Files

In [21]:
coffee = pd.read_csv("./warmup-data/coffee.csv")

In [22]:
coffee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [23]:
results = pd.read_parquet("./data/results.parquet")
# using lib pyarrow to read parquet files

In [24]:
results.head()

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,NaN
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,NaN
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,NaN
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,NaN
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,NaN

In [25]:
bios=pd.read_csv("./data/bios.csv")

In [26]:
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

In [5]:
olympics = pd.read_excel("./data/olympics-data.xlsx",sheet_name="bios")

In [6]:
olympics.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

In [7]:
olympics.tail(5)

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
145495,149222,Polina Luchnikova,2002-01-30,Serov,Sverdlovsk,RUS,ROC,167.0,61.0,NaN
145496,149223,Valeriya Merkusheva,1999-09-20,Moskva (Moscow),Moskva,RUS,ROC,168.0,65.0,NaN
145497,149224,Yuliya Smirnova,1998-05-08,Kotlas,Arkhangelsk,RUS,ROC,163.0,55.0,NaN
145498,149225,André Foussard,1899-05-19,Niort,Deux-Sèvres,FRA,France,166.0,NaN,1986-03-18
145499,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN,2003-10-20

### Accessing Data

In [27]:
print(coffee)

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [32]:
coffee.sample(5) # random 5 rows from the dataframe

          Day Coffee Type  Units Sold
9      Friday       Latte          35
10   Saturday    Espresso          45
5   Wednesday       Latte          25
4   Wednesday    Espresso          35
7    Thursday       Latte          30

In [35]:
coffee.loc[0]

Day              Monday
Coffee Type    Espresso
Units Sold           25
Name: 0, dtype: object

In [36]:
coffee.loc[0, "Coffee Type"] # accessing specific value using loc

'Espresso'

In [37]:
coffee.loc[[0,1,2]]

       Day Coffee Type  Units Sold
0   Monday    Espresso          25
1   Monday       Latte          15
2  Tuesday    Espresso          30

### iloc (index loc)

In [38]:
coffee.iloc[0,1]

'Espresso'

In [40]:
coffee.iloc[:, 0:2] # all rows, first two columns

          Day Coffee Type
0      Monday    Espresso
1      Monday       Latte
2     Tuesday    Espresso
3     Tuesday       Latte
4   Wednesday    Espresso
5   Wednesday       Latte
6    Thursday    Espresso
7    Thursday       Latte
8      Friday    Espresso
9      Friday       Latte
10   Saturday    Espresso
11   Saturday       Latte
12     Sunday    Espresso
13     Sunday       Latte

In [41]:
coffee.index = coffee["Day"]

In [42]:
coffee.head()

                 Day Coffee Type  Units Sold
Day
Monday        Monday    Espresso          25
Monday        Monday       Latte          15
Tuesday      Tuesday    Espresso          30
Tuesday      Tuesday       Latte          20
Wednesday  Wednesday    Espresso          35

In [ ]:
coffee.loc["Monday","Coffee Type"] # don't support index in loc

Day
Monday    Espresso
Monday       Latte
Name: Coffee Type, dtype: str

In [48]:
coffee=pd.read_csv("./warmup-data/coffee.csv")

In [49]:
coffee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [50]:
coffee.loc[1:3,"Units Sold"] = 10

In [51]:
coffee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          10
2    Tuesday    Espresso          10
3    Tuesday       Latte          10
4  Wednesday    Espresso          35

In [52]:
coffee.Day

0        Monday
1        Monday
2       Tuesday
3       Tuesday
4     Wednesday
5     Wednesday
6      Thursday
7      Thursday
8        Friday
9        Friday
10     Saturday
11     Saturday
12       Sunday
13       Sunday
Name: Day, dtype: str

In [54]:
s=coffee["Coffee Type"] # accessing column using column name

In [55]:
s.head()

0    Espresso
1       Latte
2    Espresso
3       Latte
4    Espresso
Name: Coffee Type, dtype: str

In [ ]:
 coffee.sort_values(by="Units Sold", ascending=True) # sort dataframe by Units Sold in ascending order

          Day Coffee Type  Units Sold
1      Monday       Latte          10
2     Tuesday    Espresso          10
3     Tuesday       Latte          10
0      Monday    Espresso          25
5   Wednesday       Latte          25
7    Thursday       Latte          30
4   Wednesday    Espresso          35
9      Friday       Latte          35
13     Sunday       Latte          35
11   Saturday       Latte          35
6    Thursday    Espresso          40
8      Friday    Espresso          45
10   Saturday    Espresso          45
12     Sunday    Espresso          45

In [58]:
coffee.sort_values(["Units Sold","Coffee Type"], ascending=[0,1])

          Day Coffee Type  Units Sold
8      Friday    Espresso          45
10   Saturday    Espresso          45
12     Sunday    Espresso          45
6    Thursday    Espresso          40
4   Wednesday    Espresso          35
9      Friday       Latte          35
11   Saturday       Latte          35
13     Sunday       Latte          35
7    Thursday       Latte          30
0      Monday    Espresso          25
5   Wednesday       Latte          25
2     Tuesday    Espresso          10
1      Monday       Latte          10
3     Tuesday       Latte          10

In [59]:
for index, row in coffee.iterrows():
    print(index, row["Coffee Type"], row["Units Sold"])

0 Espresso 25
1 Latte 10
2 Espresso 10
3 Latte 10
4 Espresso 35
5 Latte 25
6 Espresso 40
7 Latte 30
8 Espresso 45
9 Latte 35
10 Espresso 45
11 Latte 35
12 Espresso 45
13 Latte 35

### Data Filtering