In [1]:
import pandas as pd

In [ ]:
# [[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]] 
# raw format hard to read

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15]]

In [9]:
df= pd.DataFrame([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]], columns=['A','B','C'], index=['row1','row2','row3','row4','row5'])

In [10]:
df

       A   B   C
row1   1   2   3
row2   4   5   6
row3   7   8   9
row4  10  11  12
row5  13  14  15

In [11]:
df.head(3) # top 3 rows

      A  B  C
row1  1  2  3
row2  4  5  6
row3  7  8  9

In [12]:
df.tail(2) # bottom 2 rows

       A   B   C
row4  10  11  12
row5  13  14  15

In [13]:
df.columns # column names

Index(['A', 'B', 'C'], dtype='str')

In [15]:
df.columns.tolist() # column names in list format

['A', 'B', 'C']

In [16]:
df.index.to_list() # index names in list format

['row1', 'row2', 'row3', 'row4', 'row5']

In [17]:
df.info() # info about the dataframe

<class 'pandas.DataFrame'>
Index: 5 entries, row1 to row5
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       5 non-null      int64
 1   B       5 non-null      int64
 2   C       5 non-null      int64
dtypes: int64(3)
memory usage: 180.0 bytes

In [18]:
df.describe() # statistical summary of the dataframe

               A          B          C
count   5.000000   5.000000   5.000000
mean    7.000000   8.000000   9.000000
std     4.743416   4.743416   4.743416
min     1.000000   2.000000   3.000000
25%     4.000000   5.000000   6.000000
50%     7.000000   8.000000   9.000000
75%    10.000000  11.000000  12.000000
max    13.000000  14.000000  15.000000

In [19]:
df.nunique() # number of unique values in each column

A    5
B    5
C    5
dtype: int64

In [20]:
df["A"]

row1     1
row2     4
row3     7
row4    10
row5    13
Name: A, dtype: int64

In [17]:
df["A"].nunique() # number of unique values in column A

5

In [18]:
df["A"].unique() # unique values in column A

array([ 1,  4,  7, 10, 13])

In [19]:
df.shape # number of rows and columns in the dataframe

(5, 3)

In [20]:
df.size # number of elements in the dataframe

15

### Loading in Dataframes from Files

In [21]:
coffee = pd.read_csv("./warmup-data/coffee.csv")

In [22]:
coffee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [23]:
results = pd.read_parquet("./data/results.parquet")
# using lib pyarrow to read parquet files

In [24]:
results.head()

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,NaN
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,NaN
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,NaN
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,NaN
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,NaN

In [25]:
bios=pd.read_csv("./data/bios.csv")

In [26]:
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

In [5]:
olympics = pd.read_excel("./data/olympics-data.xlsx",sheet_name="bios")

In [6]:
olympics.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

In [7]:
olympics.tail(5)

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
145495,149222,Polina Luchnikova,2002-01-30,Serov,Sverdlovsk,RUS,ROC,167.0,61.0,NaN
145496,149223,Valeriya Merkusheva,1999-09-20,Moskva (Moscow),Moskva,RUS,ROC,168.0,65.0,NaN
145497,149224,Yuliya Smirnova,1998-05-08,Kotlas,Arkhangelsk,RUS,ROC,163.0,55.0,NaN
145498,149225,André Foussard,1899-05-19,Niort,Deux-Sèvres,FRA,France,166.0,NaN,1986-03-18
145499,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN,2003-10-20

### Accessing Data

In [27]:
print(coffee)

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [32]:
coffee.sample(5) # random 5 rows from the dataframe

          Day Coffee Type  Units Sold
9      Friday       Latte          35
10   Saturday    Espresso          45
5   Wednesday       Latte          25
4   Wednesday    Espresso          35
7    Thursday       Latte          30

In [35]:
coffee.loc[0]

Day              Monday
Coffee Type    Espresso
Units Sold           25
Name: 0, dtype: object

In [36]:
coffee.loc[0, "Coffee Type"] # accessing specific value using loc

'Espresso'

In [37]:
coffee.loc[[0,1,2]]

       Day Coffee Type  Units Sold
0   Monday    Espresso          25
1   Monday       Latte          15
2  Tuesday    Espresso          30

### iloc (index loc)

In [38]:
coffee.iloc[0,1]

'Espresso'

In [40]:
coffee.iloc[:, 0:2] # all rows, first two columns

          Day Coffee Type
0      Monday    Espresso
1      Monday       Latte
2     Tuesday    Espresso
3     Tuesday       Latte
4   Wednesday    Espresso
5   Wednesday       Latte
6    Thursday    Espresso
7    Thursday       Latte
8      Friday    Espresso
9      Friday       Latte
10   Saturday    Espresso
11   Saturday       Latte
12     Sunday    Espresso
13     Sunday       Latte

In [41]:
coffee.index = coffee["Day"]

In [42]:
coffee.head()

                 Day Coffee Type  Units Sold
Day
Monday        Monday    Espresso          25
Monday        Monday       Latte          15
Tuesday      Tuesday    Espresso          30
Tuesday      Tuesday       Latte          20
Wednesday  Wednesday    Espresso          35

In [ ]:
coffee.loc["Monday","Coffee Type"] # don't support index in loc

Day
Monday    Espresso
Monday       Latte
Name: Coffee Type, dtype: str

In [48]:
coffee=pd.read_csv("./warmup-data/coffee.csv")

In [49]:
coffee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [50]:
coffee.loc[1:3,"Units Sold"] = 10

In [51]:
coffee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          10
2    Tuesday    Espresso          10
3    Tuesday       Latte          10
4  Wednesday    Espresso          35

In [52]:
coffee.Day

0        Monday
1        Monday
2       Tuesday
3       Tuesday
4     Wednesday
5     Wednesday
6      Thursday
7      Thursday
8        Friday
9        Friday
10     Saturday
11     Saturday
12       Sunday
13       Sunday
Name: Day, dtype: str

In [54]:
s=coffee["Coffee Type"] # accessing column using column name

In [55]:
s.head()

0    Espresso
1       Latte
2    Espresso
3       Latte
4    Espresso
Name: Coffee Type, dtype: str

In [ ]:
 coffee.sort_values(by="Units Sold", ascending=True) # sort dataframe by Units Sold in ascending order

          Day Coffee Type  Units Sold
1      Monday       Latte          10
2     Tuesday    Espresso          10
3     Tuesday       Latte          10
0      Monday    Espresso          25
5   Wednesday       Latte          25
7    Thursday       Latte          30
4   Wednesday    Espresso          35
9      Friday       Latte          35
13     Sunday       Latte          35
11   Saturday       Latte          35
6    Thursday    Espresso          40
8      Friday    Espresso          45
10   Saturday    Espresso          45
12     Sunday    Espresso          45

In [58]:
coffee.sort_values(["Units Sold","Coffee Type"], ascending=[0,1])

          Day Coffee Type  Units Sold
8      Friday    Espresso          45
10   Saturday    Espresso          45
12     Sunday    Espresso          45
6    Thursday    Espresso          40
4   Wednesday    Espresso          35
9      Friday       Latte          35
11   Saturday       Latte          35
13     Sunday       Latte          35
7    Thursday       Latte          30
0      Monday    Espresso          25
5   Wednesday       Latte          25
2     Tuesday    Espresso          10
1      Monday       Latte          10
3     Tuesday       Latte          10

In [59]:
for index, row in coffee.iterrows():
    print(index, row["Coffee Type"], row["Units Sold"])

0 Espresso 25
1 Latte 10
2 Espresso 10
3 Latte 10
4 Espresso 35
5 Latte 25
6 Espresso 40
7 Latte 30
8 Espresso 45
9 Latte 35
10 Espresso 45
11 Latte 35
12 Espresso 45
13 Latte 35

### Data Filtering

In [60]:
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

In [61]:
bios.shape

(145500, 10)

In [63]:
temp = bios.loc[bios["height_cm"] >215] # filter rows where height_cm is greater than 215
temp.shape

(35, 10)

In [64]:
temp.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
5089,5108,Viktor Pankrashkin,1957-06-19,Moskva (Moscow),Moskva,RUS,Soviet Union,220.0,112.0,1993-07-24
5583,5606,Paulinho Villas Boas,1963-01-26,São Paulo,São Paulo,BRA,Brazil,217.0,106.0,NaN
5673,5696,Gunther Behnke,1963-01-19,Leverkusen,Nordrhein-Westfalen,GER,Germany,221.0,114.0,NaN
5716,5739,Uwe Blab,1962-03-26,München (Munich),Bayern,GER,Germany West Germany,218.0,110.0,NaN
5781,5804,Tommy Burleson,1952-02-24,Crossnore,North Carolina,USA,United States,223.0,102.0,NaN

In [65]:
bios.loc[bios["height_cm"] >215, ["name","height_cm"]] # filter rows where height_cm is greater than 215 and select only name and height_cm columns

                         name  height_cm
5089       Viktor Pankrashkin      220.0
5583     Paulinho Villas Boas      217.0
5673           Gunther Behnke      221.0
5716                 Uwe Blab      218.0
5781           Tommy Burleson      223.0
5796            Andy Campbell      218.0
6223              Lars Hansen      216.0
6270              Hu Zhangbao      216.0
6409         Sergey Kovalenko      216.0
6420            Jānis Krūmiņš      218.0
6504              Luc Longley      220.0
6722         Shaquille O'Neal      216.0
6937           David Robinson      216.0
6978          Arvydas Sabonis      223.0
7074           Paulo da Silva      217.0
7188       Vladimir Tkachenko      220.0
7281         Stojko Vranković      217.0
7376      Eurelijus Žukauskas      218.0
52608         Aleksey Kazakov      217.0
82100           Frédéric Weis      218.0
89070                Yao Ming      226.0
89075          Roberto Dueñas      221.0
107408       Peter John Ramos      219.0
112312           Stanko Barać      217.0
112332    Andreas Glyniadakis      216.0
112337          Hamed Haddadi      218.0
118663         Timofey Mozgov      216.0
118676        Dmitry Musersky      219.0
120266           Zhang Zhaoxu      221.0
121694            Salah Mejri      216.0
123850         Tyson Chandler      216.0
130460               Li Muhao      218.0
130461                Zhou Qi      217.0
138671          Ondřej Balvín      216.0
139365         Moustapha Fall      218.0

### short hand index (alt of loc)

In [66]:
bios[bios["height_cm"] >215][["name","height_cm"]] # alternative way to filter rows and select columns

                         name  height_cm
5089       Viktor Pankrashkin      220.0
5583     Paulinho Villas Boas      217.0
5673           Gunther Behnke      221.0
5716                 Uwe Blab      218.0
5781           Tommy Burleson      223.0
5796            Andy Campbell      218.0
6223              Lars Hansen      216.0
6270              Hu Zhangbao      216.0
6409         Sergey Kovalenko      216.0
6420            Jānis Krūmiņš      218.0
6504              Luc Longley      220.0
6722         Shaquille O'Neal      216.0
6937           David Robinson      216.0
6978          Arvydas Sabonis      223.0
7074           Paulo da Silva      217.0
7188       Vladimir Tkachenko      220.0
7281         Stojko Vranković      217.0
7376      Eurelijus Žukauskas      218.0
52608         Aleksey Kazakov      217.0
82100           Frédéric Weis      218.0
89070                Yao Ming      226.0
89075          Roberto Dueñas      221.0
107408       Peter John Ramos      219.0
112312           Stanko Barać      217.0
112332    Andreas Glyniadakis      216.0
112337          Hamed Haddadi      218.0
118663         Timofey Mozgov      216.0
118676        Dmitry Musersky      219.0
120266           Zhang Zhaoxu      221.0
121694            Salah Mejri      216.0
123850         Tyson Chandler      216.0
130460               Li Muhao      218.0
130461                Zhou Qi      217.0
138671          Ondřej Balvín      216.0
139365         Moustapha Fall      218.0

### Multiple Filter conditions

In [67]:
bios[(bios["height_cm"] > 215) & (bios['born_country'] == 'USA')]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
5781,5804,Tommy Burleson,1952-02-24,Crossnore,North Carolina,USA,United States,223.0,102.0,NaN
6722,6755,Shaquille O'Neal,1972-03-06,Newark,New Jersey,USA,United States,216.0,137.0,NaN
6937,6972,David Robinson,1965-08-06,Key West,Florida,USA,United States,216.0,107.0,NaN
123850,126093,Tyson Chandler,1982-10-02,Hanford,California,USA,United States,216.0,107.0,NaN

### Filter by string conditions

In [69]:
bios[bios["name"].str.contains("Navin", case=False)] # filter rows where name contains "Smith"

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
50589,50948,Carlos Scanavino,1964-03-11,Paysandú,Paysandú,URU,Uruguay,187.0,80.0,NaN
58998,59421,Navind Ramsaran,1961-04-10,NaN,NaN,NaN,Mauritius,186.0,115.0,NaN
107468,108595,Navina Omilade,1981-11-03,Mönchengladbach,Nordrhein-Westfalen,GER,Germany,176.0,63.0,NaN
111054,112285,Antonella Scanavino,1992-10-30,Maldonado,Maldonado,URU,Uruguay,166.0,60.0,NaN

### New Query Func

In [70]:
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

In [71]:
bios.query('born_country == "USA" and height_cm > 215') # filter rows where born_country is USA and height_cm is greater than 215 using query function

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
5781,5804,Tommy Burleson,1952-02-24,Crossnore,North Carolina,USA,United States,223.0,102.0,NaN
6722,6755,Shaquille O'Neal,1972-03-06,Newark,New Jersey,USA,United States,216.0,137.0,NaN
6937,6972,David Robinson,1965-08-06,Key West,Florida,USA,United States,216.0,107.0,NaN
123850,126093,Tyson Chandler,1982-10-02,Hanford,California,USA,United States,216.0,107.0,NaN

### Adding/Removing Columns

In [72]:
coffee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          10
2    Tuesday    Espresso          10
3    Tuesday       Latte          10
4  Wednesday    Espresso          35

In [73]:
coffee["price"]=4.99

In [74]:
coffee.head()

         Day Coffee Type  Units Sold  price
0     Monday    Espresso          25   4.99
1     Monday       Latte          10   4.99
2    Tuesday    Espresso          10   4.99
3    Tuesday       Latte          10   4.99
4  Wednesday    Espresso          35   4.99

In [75]:
import numpy as np

In [77]:
coffee["new_price"] = np.where(coffee["Coffee Type"] == "Espresso",3.99,5.99)

In [78]:
coffee.head(7)

         Day Coffee Type  Units Sold  price  new_price
0     Monday    Espresso          25   4.99       3.99
1     Monday       Latte          10   4.99       5.99
2    Tuesday    Espresso          10   4.99       3.99
3    Tuesday       Latte          10   4.99       5.99
4  Wednesday    Espresso          35   4.99       3.99
5  Wednesday       Latte          25   4.99       5.99
6   Thursday    Espresso          40   4.99       3.99

In [ ]:
coffee.drop(columns=["price"], inplace=True) # drop the price column
# inplace=True will modify the original dataframe, if inplace=False it will return a new dataframe with the column dropped but the original dataframe will remain unchanged
# for permanent delete use inline=True

KeyError: "['price'] not found in axis"

In [82]:
coffee.head()

         Day Coffee Type  Units Sold  new_price
0     Monday    Espresso          25       3.99
1     Monday       Latte          10       5.99
2    Tuesday    Espresso          10       3.99
3    Tuesday       Latte          10       5.99
4  Wednesday    Espresso          35       3.99

In [83]:
coffee["revenue"]=coffee["Units Sold"]*coffee["new_price"]

In [84]:
coffee.head()

         Day Coffee Type  Units Sold  new_price  revenue
0     Monday    Espresso          25       3.99    99.75
1     Monday       Latte          10       5.99    59.90
2    Tuesday    Espresso          10       3.99    39.90
3    Tuesday       Latte          10       5.99    59.90
4  Wednesday    Espresso          35       3.99   139.65

In [85]:
# rename
coffee.rename(columns={"new_price":"price"}, inplace=True)

In [86]:
coffee.head()

         Day Coffee Type  Units Sold  price  revenue
0     Monday    Espresso          25   3.99    99.75
1     Monday       Latte          10   5.99    59.90
2    Tuesday    Espresso          10   3.99    39.90
3    Tuesday       Latte          10   5.99    59.90
4  Wednesday    Espresso          35   3.99   139.65

In [87]:
bios.info()

<class 'pandas.DataFrame'>
RangeIndex: 145500 entries, 0 to 145499
Data columns (total 10 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   athlete_id    145500 non-null  int64
 1   name          145500 non-null  str
 2   born_date     143693 non-null  str
 3   born_city     110908 non-null  str
 4   born_region   110908 non-null  str
 5   born_country  110908 non-null  str
 6   NOC           145499 non-null  str
 7   height_cm     106651 non-null  float64
 8   weight_kg     102070 non-null  float64
 9   died_date     33940 non-null   str
dtypes: float64(2), int64(1), str(7)
memory usage: 18.5 MB

In [92]:
bios["died_datetime"]=pd.to_datetime(bios["died_date"])

In [93]:
bios.info()

<class 'pandas.DataFrame'>
RangeIndex: 145500 entries, 0 to 145499
Data columns (total 12 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   athlete_id     145500 non-null  int64
 1   name           145500 non-null  str
 2   born_date      143693 non-null  str
 3   born_city      110908 non-null  str
 4   born_region    110908 non-null  str
 5   born_country   110908 non-null  str
 6   NOC            145499 non-null  str
 7   height_cm      106651 non-null  float64
 8   weight_kg      102070 non-null  float64
 9   died_date      33940 non-null   str
 10  born_datetime  33940 non-null   datetime64[us]
 11  died_datetime  33940 non-null   datetime64[us]
dtypes: datetime64[us](2), float64(2), int64(1), str(7)
memory usage: 20.7 MB

In [94]:
bios["died_year"]=bios["died_datetime"].dt.year

In [95]:
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,born_datetime,died_datetime,died_year
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,1960-10-02,1960-10-02,1960.0
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,NaT,NaT,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,1994-07-17,1994-07-17,1994.0
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,1978-03-20,1978-03-20,1978.0
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,1930-07-25,1930-07-25,1930.0

In [96]:
# saving the file
bios.to_csv("./data/temp_bios.csv", index=False) # save the dataframe to a csv file without the index column

In [97]:
def categorized_athlete(row):
    if row["height_cm"]<175 and row["weight_kg"]<70:
        return "Lightweight"
    elif row["height_cm"]<185 or row["weight_kg"]<=80:
        return "Middleweight"
    else:
        return "Heavyweight"

In [99]:
bios["Category"] = bios.apply(categorized_athlete, axis=1)

In [100]:
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,born_datetime,died_datetime,died_year,Category
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,1960-10-02,1960-10-02,1960.0,Heavyweight
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,NaT,NaT,NaN,Middleweight
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,1994-07-17,1994-07-17,1994.0,Middleweight
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,1978-03-20,1978-03-20,1978.0,Lightweight
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,1930-07-25,1930-07-25,1930.0,Heavyweight

### Merging & Concat Data

In [101]:
nocs = pd.read_csv("./data/noc_regions.csv")

In [102]:
nocs.head()

   NOC       region                 notes
0  AFG  Afghanistan                   NaN
1  AHO      Curacao  Netherlands Antilles
2  ALB      Albania                   NaN
3  ALG      Algeria                   NaN
4  AND      Andorra                   NaN

In [103]:
bios_new = pd.merge(bios,nocs,  left_on ="born_country", right_on= "NOC")

In [104]:
bios_new.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC_x,height_cm,weight_kg,died_date,born_datetime,died_datetime,died_year,Category,NOC_y,region,notes
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,1960-10-02,1960-10-02,1960.0,Heavyweight,FRA,France,NaN
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,NaT,NaT,NaN,Middleweight,FRA,France,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,1994-07-17,1994-07-17,1994.0,Middleweight,FRA,France,NaN
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,1978-03-20,1978-03-20,1978.0,Lightweight,FRA,France,NaN
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,1930-07-25,1930-07-25,1930.0,Heavyweight,GBR,UK,NaN

### Handling Null Values

In [105]:
coffee.isnull().sum()

Day            0
Coffee Type    0
Units Sold     0
price          0
revenue        0
dtype: int64

In [106]:
coffee.loc[[0,1,2], "Units Sold"] = np.nan

In [107]:
coffee.head()

         Day Coffee Type  Units Sold  price  revenue
0     Monday    Espresso         NaN   3.99    99.75
1     Monday       Latte         NaN   5.99    59.90
2    Tuesday    Espresso         NaN   3.99    39.90
3    Tuesday       Latte        10.0   5.99    59.90
4  Wednesday    Espresso        35.0   3.99   139.65

In [108]:
coffee.isnull().sum()

Day            0
Coffee Type    0
Units Sold     3
price          0
revenue        0
dtype: int64

In [111]:
coffee["Units Sold"].mean()

np.float64(34.54545454545455)

In [115]:
coffee.fillna({"Units Sold": coffee["Units Sold"].mean()}, inplace=True)

          Day Coffee Type  Units Sold  price  revenue
0      Monday    Espresso   34.545455   3.99    99.75
1      Monday       Latte   34.545455   5.99    59.90
2     Tuesday    Espresso   34.545455   3.99    39.90
3     Tuesday       Latte   10.000000   5.99    59.90
4   Wednesday    Espresso   35.000000   3.99   139.65
5   Wednesday       Latte   25.000000   5.99   149.75
6    Thursday    Espresso   40.000000   3.99   159.60
7    Thursday       Latte   30.000000   5.99   179.70
8      Friday    Espresso   45.000000   3.99   179.55
9      Friday       Latte   35.000000   5.99   209.65
10   Saturday    Espresso   45.000000   3.99   179.55
11   Saturday       Latte   35.000000   5.99   209.65
12     Sunday    Espresso   45.000000   3.99   179.55
13     Sunday       Latte   35.000000   5.99   209.65

In [116]:
coffee.isnull().sum()

Day            0
Coffee Type    0
Units Sold     0
price          0
revenue        0
dtype: int64

In [117]:
coffee.dropna(subset=["Units Sold"]) # drop rows where Units Sold is null

          Day Coffee Type  Units Sold  price  revenue
0      Monday    Espresso   34.545455   3.99    99.75
1      Monday       Latte   34.545455   5.99    59.90
2     Tuesday    Espresso   34.545455   3.99    39.90
3     Tuesday       Latte   10.000000   5.99    59.90
4   Wednesday    Espresso   35.000000   3.99   139.65
5   Wednesday       Latte   25.000000   5.99   149.75
6    Thursday    Espresso   40.000000   3.99   159.60
7    Thursday       Latte   30.000000   5.99   179.70
8      Friday    Espresso   45.000000   3.99   179.55
9      Friday       Latte   35.000000   5.99   209.65
10   Saturday    Espresso   45.000000   3.99   179.55
11   Saturday       Latte   35.000000   5.99   209.65
12     Sunday    Espresso   45.000000   3.99   179.55
13     Sunday       Latte   35.000000   5.99   209.65

### Aggregating Data

In [118]:
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,born_datetime,died_datetime,died_year,Category
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,1960-10-02,1960-10-02,1960.0,Heavyweight
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,NaT,NaT,NaN,Middleweight
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,1994-07-17,1994-07-17,1994.0,Middleweight
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,1978-03-20,1978-03-20,1978.0,Lightweight
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,1930-07-25,1930-07-25,1930.0,Heavyweight

In [119]:
bios["born_city"].value_counts() # count of unique values in born_city column

born_city
Budapest            1378
Moskva (Moscow)      883
Oslo                 708
Stockholm            629
Praha (Prague)       600
                    ...
Tsivilsk               1
Roth                   1
Romoos                 1
Dva Polya Artash       1
Dulwich Hill           1
Name: count, Length: 22368, dtype: int64

In [120]:
bios["born_country"].value_counts() # count of unique values in born_country column

born_country
USA       9641
GER       6891
GBR       5792
FRA       5143
ITA       4709
          ...
Havel        1
SMT          1
COK          1
Corfu        1
Aarhus       1
Name: count, Length: 236, dtype: int64

### groupby func

In [121]:
coffee.groupby(["Coffee Type"])["Units Sold"].mean() # group by Coffee Type and calculate mean of Units Sold for each group

Coffee Type
Espresso    39.870130
Latte       29.220779
Name: Units Sold, dtype: float64

### Pivot Table

In [122]:
coffee.head()

         Day Coffee Type  Units Sold  price  revenue
0     Monday    Espresso   34.545455   3.99    99.75
1     Monday       Latte   34.545455   5.99    59.90
2    Tuesday    Espresso   34.545455   3.99    39.90
3    Tuesday       Latte   10.000000   5.99    59.90
4  Wednesday    Espresso   35.000000   3.99   139.65

In [123]:
pivot = coffee.pivot(columns="Coffee Type", index="Day",values="revenue")

In [124]:
pivot

Coffee Type  Espresso   Latte
Day
Friday         179.55  209.65
Monday          99.75   59.90
Saturday       179.55  209.65
Sunday         179.55  209.65
Thursday       159.60  179.70
Tuesday         39.90   59.90
Wednesday      139.65  149.75